SELECT EMP_NAME, NVL(DEPT_TITLE,'부서없음') AS DEPT_TITLE , SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE NVL(DEPT_TITLE,'부서없음') = '부서없음';

SELECT EMP_NAME, JOB_NAME, SALARY, SALARY*12 FROM EMPLOYEE;


